version: '3'

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  backend:
    image: k3llar/cloud_fastapi:latest
    restart: always
    volumes:
      - media_value:/app/media/
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - /nginx.conf:/etc/nginx/conf.d

    depends_on:
      - backend

volumes:
  data_value:
  media_value:
