"""02_file_model

Revision ID: 9717f7321ae7
Revises: 6f76bf2b07e5
Create Date: 2022-11-02 18:30:49.424532

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9717f7321ae7'
down_revision = '6f76bf2b07e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('File_register',
    sa.Column('file_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('is_downloadable', sa.Boolean(), nullable=True),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.guid.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('path', 'user_id')
    )
    op.create_index(op.f('ix_File_register_file_name'), 'File_register', ['file_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_File_register_file_name'), table_name='File_register')
    op.drop_table('File_register')
    # ### end Alembic commands ###
